image: node:latest

stages:
  - build
  - test

build_front_end:
  stage: build
  script:
    - cd frontend
    - npm install
    - CI=false npm run-script build

postman:
  stage: test
  image:
    name: postman/newman
    entrypoint: [""]
  script:
    newman run GameHub.postman_collection.json